### ISSUE TITLE
MGS100 getting node.js error

### ISSUE THREAD

**Issue by ckuai** [donavanbecker/homebridge-meross#646]
### What issue do you have? Please be as thorough and explicit as possible.
Recently about since 2 weeks ago my wife complaining that her HomeKit is not able to control the garage door. She had to use the physical remote. and upon checking I found the Homebridge Meross is getting error whenever I try to use it to control the  Meross MSG100 garage door.  the Homekit is not able to report the garage door status and it remain in `opening` status forever after 1st operate and stuck in this status forever. In hombridge-UI, the garage door status also remain in opening status. below is the log

```
[11/28/2024, 1:16:27 PM] [Meross] [Side Garage Door] sending update failed as Parse Error: Missing expected CR after response line at Function.AxiosError.from (file:///C:/Users/ckuai/AppData/Roaming/npm/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:92:14).
```

I have 2 garage doors side by side and both have MSG100 and both now having the same error.

```
[11/28/2024, 1:18:31 PM] [Meross] [Main Garage Door] sending update failed as Parse Error: Missing expected CR after response line at Function.AxiosError.from (file:///C:/Users/ckuai/AppData/Roaming/npm/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:92:14).
```
This means the door can operate once only with either on homekit UI with a i-device or on homebridge-UI. after the 1st operation the status remain in opening and from that on I can only use the Meross app to operate the garage door. restart homebridge can reset the issue but the garage door can only be operate once and get into stuck status again.

This setup has been working for years until recently. all a sudden both my MGS100 are getting the above same error. I have resintall the hombridge-meross and downgradge to 10.7.0 but non of that fixes the issue. any help is appreciated.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
* I use Homebridge running on a Windows Server with Hombridge UI and Meross plugin

* Which version of Homebridge/HOOBS do you have?
*  HomeBridge 1.8.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known
* Windows. Node V22.11.0, npm 10.9.1

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version? 
* 10.8.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
* MGS100

### Please paste any relevant logs below.

```
[11/28/2024, 1:16:27 PM] [Meross] [Side Garage Door] sending update failed as Parse Error: Missing expected CR after response line at Function.AxiosError.from (file:///C:/Users/ckuai/AppData/Roaming/npm/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:92:14).
[11/28/2024, 1:18:31 PM] [Meross] [Main Garage Door] sending update failed as Parse Error: Missing expected CR after response line at Function.AxiosError.from (file:///C:/Users/ckuai/AppData/Roaming/npm/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:92:14).
```

**Comment by wangel** [comment]
I am having the same issue now as well :(   Wife is stuck outside in the cold, woops.

Seriously, though, same exact issue.  I can use the Meross app to open the door etc, but she only has the Home App.   Any help would be appreciated :D

**Comment by bwp91** [comment]
Looks like an immediate solution is to downgrade to node 20. I need to look into this issue further

**Comment by wangel** [comment]
Yep, I can confirm.  I rolled node back to version 20 and it works fine.  

If anyone runs across this, I ran this command:

hb-service update-node 20.18.1

**Comment by bwp91** [comment]
Hi @wangel @ckuai 

I've just published a beta version of the plugin (10.8.1-beta.0) with a change that might fix this issue with the plugin on node 22.

I'm thinking this is an issue limited to the MSG100, otherwise I think a lot more users will have reported this issue. I don't have this device, and I have had no issues with this plugin on node 22.

Not having the model also means that I cannot test the fix myself. So hoping someone would do the honours and give it a try. Remember to test it on node 22 😛

Thanks

**Comment by wangel** [comment]
Yep no problem.  I've updated to Node 22
It still fails;

[12/11/2024, 12:06:04 PM] [Meross] [Garage Door] sending update: {"header":{"from":"http://IP.ADD.XXX.XXX/config","messageId":"4d6wacg5txfjr8gp71eug4jo62ilegri","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"52fea7e4f5b65bdd7a4026f23a7a43e0","timestamp":1733936764,"triggerSrc":"iOSLocal","uuid":"2306012037076561070148e1e9c87046"},"payload":{}}.
[12/11/2024, 12:06:04 PM] [Meross] [Garage Door] failed to request status as: Parse Error: Missing expected CR after response line at Function.AxiosError.from (file:///usr/lib/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:92:14).

Going back to Node 20 works.  I have a snapshot of my homebridge VM if you want to continue testing :)

I think you are correct in this only is an issue for people with a MSG100..  That's what I get for being cheap, lol!

**Comment by bwp91** [comment]
@wangel does controlling the device from homekit work?

**Comment by bwp91** [comment]
also @wangel do you have the `homebridge-meross` plugin version installed or the `@homebridge-plugins/homebridge-meross`?

They are exactly the same, so don't worry about which one you are on or which you _should_ be.

**Comment by wangel** [comment]
@bwp91 ; I can control the device through Homekit now, but the status won't update.

Right now the door is open.  I click it, and it does close it, homekit shows "closing..." and then, even though the door is closed, it reverts back to Open.  Clicking it again, does  open the door ... so controlling seems to be working now :)

As for the plugin, I installed it from the Config-UI gui, so it should be pulling the github repo ?

**Comment by bwp91** [comment]
@wangel thanks for the report, i've just published another beta to try for the status updates, can you try `10.8.1-beta.2`? it might take a few minutes to appear available in the UI.

**Comment by wangel** [comment]
@bwp91 it appears Beta2 fixed the issue.

It's chatty, do you need any debug information ?   The updates are working etc now and there are no more Parse Error messages.

Thank you sir!!!

**Comment by bwp91** [comment]
Fixed in `10.8.1` which will also set the logging back to normal (beta versions have more logging by default)

**Comment by ckuai** [comment]
Thanks for the fix. Verified everything is working @10.8.1
